version: '3.8'
services:
  bronze:
    build: ./bronze
    command: python app.py
    volumes:
      - ./bronze:/app
    ports:
      - "8081:8080"
    environment:
      - GOOGLE_DRIVE_FILE_ID=1E7iRwCp7IjvCjh_-owrt2NTMWnvgleZp
      - PORT=8080
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - SILVER_URL=http://silver:8080
      - ENVIRONMENT=dev

  silver:
    build: ./silver
    command: python app.py
    volumes:
      - ./silver:/app
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - MONGO_DB=reddit_analytics
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword


  gold:
    build: ./gold
    command: python app.py
    volumes:
      - ./gold:/app
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://root:rootpassword@mongodb_container:27017/
      - MONGO_DB=reddit_analytics
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:


  # pubsub-emulator:
  #   image: google/cloud-sdk:latest
  #   ports:
  #     - "8085:8085"
  #   volumes:
  #     - ./utils/pubsub-setup.sh:/pubsub-setup.sh
  #   command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
  #   environment:
  #     - CLOUDSDK_CORE_PROJECT=fake-project