version: '3.8'
services:
  flask-app:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_DRIVE_FILE_ID=your_id_here
      - PORT=8080